### PR TITLE
Update TLDs.

### LINKED ISSUE #5: [Bug] Server::getServerByTld() failed with unknown TLD
Hello. If I tried to execute `(new Whois('ANY_DOMAIN.website'))->lookup();`, this will cause a Type error in PHP

> PhpWhois\Server::getServerByTld(): Return value must be of type string, null returned

Because `getServerByTld` expect to be return only strings, but there is no `website` TLD into an array of known.
https://github.com/petk/phpwhois/blob/master/src/Server.php#L299-L302

Possible solution: add `??` operator to the method.

### PR DESCRIPTION
**Pull request by Aliance**
Closes https://github.com/petk/phpwhois/issues/5

@petk review please

I got the list from [open source](https://raw.githubusercontent.com/phpWhois/phpWhois/master/src/whois.servers.php)

### CODE REVIEW

**Review by petk — APPROVED** [review]
Thank you @Aliance

**Comment by Aliance** [comment]
Thanks! Can you make a new release?

**Comment by Aliance** [comment]
@petk without a release we can not download new version :)

_I meant without using `dev-master` alias_

**Comment by petk** [comment]
Coming up...

**Comment by petk** [comment]
v0.0.2 has been tagged for now. Probably I should also sync the composer.json file and the version string in one of the source files at some point in the future.

**Pull request merged**
